export const modelImageGens = [
  "dall-e-3",
  "gemini-2.5-flash-image-preview (nano-banana)",
  "gemini-2.5-flash-image-preview",
  "imagen-4.0-generate-preview-06-06",
  "flux",
  "turbo",
  "kontext",
  "flux-dev",
  "flux-kontext-dev",
  "flux-1-kontext-dev",
  "imagen-3.0-generate-002",
  "ideogram-v2",
  "photon",
  "recraft-v3",
  "anonymous-bot-0514",
  "flux-1.1-pro",
  "ideogram-v3-quality",
  "seedream-3",
  "lucid-origin",
  "gpt-image-1",
  "imagen-4.0-ultra-generate-preview-06-06",
  "gemini-2.0-flash-preview-image-generation",
  "flux-1-kontext-pro",
  "qwen-image-prompt-extend",
  "flux-1-kontext-max",
  "qwen-image-edit",
  "nano-banana",
  "seededit-3.0",
  "hidream-e1.1",
  "sd-3.5-large",
]
export function getImageModels() {
  return modelImageGens
}
